### ISSUE TITLE
Prepare an SLO/SLI file that checks whether the Problem has been closed (as part of the remediation process)

### ISSUE THREAD

**Issue by johannes-b** [keptn/examples#165]
**User story:** As a user, I want to see a failed evaluation when a Dynatrace problem for the service is still open.

*When using Dynatrace for problem detection:* 

The dynatrace-sli-service sends the number of open problems when fetching SLI values in course of a remediation process. The number of open problems should be taken into consideration when doing the evaluation task. Therefore, adapt the SLO (`slo-self-healing.yaml`) to contain a check for the open problems: 
```
  - sli: "problem_open"
    displayName: "Problem open"
    key_sli: true
    pass:             
      - criteria:
          - "=0"  
    weight: 1
```

Since the prometheus-sli-services does not return the number of open problems, a separate `slo-self-healing.yaml` file must be provided for this example. 

**Task:**
- Change the `slo-self-healing.yaml` for Dynatrace
- Adapt the tutorials accordingly

**Definition of Done:**
- [ ] When doing the self-healing tutorial with Dynatrace, the number of open problems is considered as part of the evaluation step
