### ISSUE TITLE
Use Kubernetes recommended labels

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/examples#91]
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

Those labels could be used as follows:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: carts
  namespace: sockshop-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carts
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: carts
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: carts-canary
        app.kubernetes.io/managed-by: Keptn
        app.kubernetes.io/name: carts
        app.kubernetes.io/part-of: sockshop
...
```
